// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtwSNNUL9BF1JYr4nKF2FLwi1G3XrAUb8',
    appId: '1:991461199602:web:db4a14d3c7bc6ac24e8a6b',
    messagingSenderId: '991461199602',
    projectId: 'mainfirebase-38119',
    authDomain: 'mainfirebase-38119.firebaseapp.com',
    storageBucket: 'mainfirebase-38119.appspot.com',
    measurementId: 'G-DN39WJELBS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1KMl8f3acPonFrw4apEQpfMZiW3FxVDE',
    appId: '1:991461199602:android:0d5f382872029cd84e8a6b',
    messagingSenderId: '991461199602',
    projectId: 'mainfirebase-38119',
    storageBucket: 'mainfirebase-38119.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5sRB9BL4ou3w0_UBTjaCqaXw8XfaDcPI',
    appId: '1:991461199602:ios:bfbdf3a11b04ef704e8a6b',
    messagingSenderId: '991461199602',
    projectId: 'mainfirebase-38119',
    storageBucket: 'mainfirebase-38119.appspot.com',
    iosClientId: '991461199602-lag345galr90m66n6b7r3h3e7hvvvp6m.apps.googleusercontent.com',
    iosBundleId: 'com.example.secondfirebaseproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5sRB9BL4ou3w0_UBTjaCqaXw8XfaDcPI',
    appId: '1:991461199602:ios:bfbdf3a11b04ef704e8a6b',
    messagingSenderId: '991461199602',
    projectId: 'mainfirebase-38119',
    storageBucket: 'mainfirebase-38119.appspot.com',
    iosClientId: '991461199602-lag345galr90m66n6b7r3h3e7hvvvp6m.apps.googleusercontent.com',
    iosBundleId: 'com.example.secondfirebaseproject',
  );
}
